### ISSUE TITLE
Option to export to MOD/XM?

### ISSUE THREAD

**Issue by AntonioND** [DavW/autotracker#1]
It would be great to be able to save the songs.

**Comment by vitling** [comment]
Please see the note in the README about feature requests

**Comment by vitling** [comment]
This is an art project, not a software tool for making music. The code is provided for educational and inspirational purposes, but I generally do not accept feature requests for any of my work released as Creative Commons (some of my work is "software" and "libraries", which are licensed under GPL3 or Apache and for which I do accept feature requests).

I do, of course, encourage you to fork it and add that capability if that's something you're interested in exploring yourself.
